events {
    worker_connections 1024;
}
http {
    upstream sicepat-backend {
        least_conn;
        server backend-checkout:8000;
        server backend-katalog:8000;
        server backend-cart:8000;
    }
    server {
        listen 80;
        location / {
            proxy_pass http://sicepat-backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}